import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import s from 'styles'
import Header from 'components/Header'
import Engineering from "jobs/engineering";
import Design from "jobs/design";
import Others from "jobs/others";
import Marketing from "jobs/marketing";
import FirstFrame from 'components/Job/FirstFrame'
interface IJobs {
  job: any
  id: any
}

const orderTabs = ["Design", "Engineering", "Marketing", "Others"]
const selectTabs = {
  Design: Design,
  Engineering: Engineering,
  Marketing: Marketing,
  Others: Others,
}  

const Job: NextPage<IJobs> = ({job}) => {
  return (
    <div>
      <Head>
        <title>Destoria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dest-favicon.png" />
      </Head>
      <FirstFrame job={job} />
      <main>
      </main>
    </div>
  )
}

export async function getStaticPaths() {
  const myArr: any[] = []
  Object.values(selectTabs).forEach(typeOfProfessional => {
    typeOfProfessional.forEach(professional => {
      myArr.push({params: {id: professional.id.toString()}})
    })
  })
  return {
    paths: myArr,
    fallback: false
  };
}

export async function getStaticProps({params}) {
  let profession
  Object.values(selectTabs).forEach(typeOfProfessional => {
    typeOfProfessional.forEach(professional => {
      if (professional.id.toString() == params.id) profession = professional
    })
  })
  return {
    props: {
      job: profession
    },
  };
}



export default Job
