import type { NextPage } from 'next'
import Head from 'next/head'

import FirstFrame from 'components/404/FirstFrame'
import MintDescription from 'components/404/MintDescription'

const Mint: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Destoria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dest-favicon.png" />
      </Head>
      <FirstFrame />
    </div>
  )
}

export default Mint