import type { NextPage } from 'next'
import Head from 'next/head'

import FirstFrame from 'components/Mint/FirstFrame'
import MintDescription from 'components/Mint/MintDescription'
import Footer
  from 'components/Footer'
const Mint: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Destoria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dest-favicon.svg" />
      </Head>
      <FirstFrame />
      <div className="bg-mint-two bg-no-repeat">
      <MintDescription />
      <Footer />
      </div>
      <main>
      </main>
    </div>
  )
}

export default Mint